//! Dynamic workflow engine — the model writes an orchestration plan on the fly;
//! the engine executes it deterministically with a fleet of parallel subagents.
//!
//! Inspired by Claude Code's research-preview "dynamic workflows" feature.
//!
//! # Architecture
//!
//! 1. **Trigger** (`trigger.rs`) — keyword detection or complexity threshold.
//! 2. **Plan** (`plan.rs`) — `WorkflowPlan` / `Phase` / `Task` types;
//!    generated by the model via the `workflow_plan` structured-output tool.
//! 3. **Engine** (`engine.rs`) — executes the plan: parallel / pipeline /
//!    sequential phase modes; bounded concurrency (max 16 simultaneous agents).
//! 4. **Tools** (`tools.rs`) — `workflow_plan` tool for model-side plan generation.
//! 5. **Trace** (`trace.rs`) — links sub-rollout bundles under a `WorkflowId`.
//!
//! See `docs/plan/05e-dynamic-workflows.md` for the full specification.
//! See `docs/plan/10e-workflow-training-dataset.md` for training data.

mod engine;
mod plan;
mod tools;
mod trace;
mod trigger;

pub use engine::{WorkflowEngine, WorkflowEngineConfig, WorkflowResult};
pub use plan::{PhaseMode, WorkflowPhase, WorkflowPlan, WorkflowTask};
pub use tools::WorkflowPlanTool;
pub use trace::{WorkflowId, WorkflowTrace};
pub use trigger::WorkflowTrigger;
